# Generated by Django 2.2.12 on 2021-10-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backup_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(default='', max_length=100, verbose_name='备份文件名')),
                ('time', models.CharField(default='', max_length=50, verbose_name='备份时间')),
                ('path', models.TextField(default='', verbose_name='备份存放路径')),
                ('size', models.CharField(default='', max_length=50, verbose_name='文件大小')),
            ],
        ),
        migrations.CreateModel(
            name='deploys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='依赖名称')),
                ('status', models.CharField(default='', max_length=50, verbose_name='依赖状态')),
                ('age', models.CharField(default='', max_length=100, verbose_name='存活时间')),
                ('namespace', models.CharField(default='default', max_length=100, verbose_name='所属命名空间')),
            ],
            options={
                'db_table': 'deploys',
            },
        ),
        migrations.CreateModel(
            name='log_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='', verbose_name='文件名')),
                ('path', models.CharField(default='', max_length=255, verbose_name='文件路径')),
                ('path_2', models.TextField(default='', verbose_name='所属目录')),
                ('size', models.TextField(default='', verbose_name='文件大小')),
                ('type', models.TextField(default='', verbose_name='类型')),
                ('time', models.TextField(default='', verbose_name='最后修改时间')),
            ],
            options={
                'db_table': 'log_file',
            },
        ),
        migrations.CreateModel(
            name='name_spaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='', max_length=50, verbose_name='命名空间')),
                ('status', models.CharField(default='Active', max_length=50, verbose_name='confirm to it is alive!')),
            ],
            options={
                'db_table': 'namespaces',
            },
        ),
        migrations.CreateModel(
            name='nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='节点名称')),
                ('status', models.CharField(default='', max_length=50, verbose_name='节点状态')),
            ],
            options={
                'db_table': 'nodes',
            },
        ),
        migrations.CreateModel(
            name='pods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='', max_length=50, verbose_name='命名空间')),
                ('pod_ip', models.CharField(default='NotReady', max_length=50, verbose_name='Pods_IP')),
                ('pod_name', models.CharField(default='', max_length=100, verbose_name='Pods_Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='confirm to delete!')),
                ('status', models.CharField(default='', max_length=50, verbose_name='STATUS')),
            ],
            options={
                'db_table': 'pods',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='None', max_length=50, verbose_name='服务类型')),
                ('namespace', models.CharField(default='', max_length=50, verbose_name='命名空间')),
                ('spec_cluster_ip', models.CharField(default='', max_length=50, verbose_name='Cluster_ip')),
                ('out_port', models.CharField(default='', max_length=100, verbose_name='暴露端口')),
                ('in_port', models.CharField(default='', max_length=100, verbose_name='占用端口')),
                ('service_name', models.CharField(default='', max_length=100, verbose_name='服务名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='confirm to delete!')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=50, verbose_name='密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='confirm to delete!')),
                ('is_root', models.BooleanField(default=False, verbose_name='confirm its admin')),
            ],
            options={
                'db_table': 'user_inf',
            },
        ),
    ]
