# Generated by Django 2.2.12 on 2021-11-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernete', '0002_hosts'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosts',
            name='host_status',
            field=models.BooleanField(default=True),
        ),
    ]
