# Generated by Django 2.2.12 on 2021-11-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernete', '0003_hosts_host_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup_log',
            name='host',
            field=models.CharField(default='', max_length=50, verbose_name='所在主机'),
        ),
    ]
