# Generated by Django 2.2.12 on 2022-01-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernete', '0004_backup_log_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='host_status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
