# Generated by Django 2.2.12 on 2022-01-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernete', '0005_auto_20220117_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_file',
            name='host',
            field=models.CharField(default='', max_length=50, verbose_name='所属主机IP'),
        ),
    ]
