# Generated by Django 2.2.12 on 2022-01-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kubernete', '0007_auto_20220119_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='get_log',
        ),
    ]
