# Generated by Django 2.2.12 on 2022-01-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kubernete', '0008_delete_get_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, verbose_name='目录')),
                ('time', models.CharField(max_length=50, verbose_name='上次刷新时间')),
                ('host', models.CharField(default='', max_length=50, verbose_name='所属主机IP')),
            ],
            options={
                'db_table': 'get_log',
            },
        ),
    ]
